### ISSUE TITLE
replace

### ISSUE THREAD

**Issue by Klausmd5** [EinboeckFranz/Hue13-TicTacToeGame#1]
replace 

` @Override
    public void onClick(View view) {
        Button button;
        String idAsString;
        Pattern p;
        Matcher m;
        int row;
        int column;

        button = (Button) view;
        idAsString = view.getResources().getResourceName(button.getId());
        p = Pattern.compile("-?\\d+");
        m = p.matcher(idAsString);
        row = Integer.parseInt(m.group());
        column = Integer.parseInt(m.group());
        game.doMove(row, column, convertButtonsArrToPlayerArray(buttons));
    }
`

with 

`protected void onCreate(Bundle savedInstanceState) { 

button = view.getElementById("btn-id");

button.setOnClickListener(() -> { click });

}
`

**Comment by EinboeckFranz** [comment]
hmm, i guess that won't help. But ty anyways
